### ISSUE TITLE
The ModularisTestUnitTests project reference a file that is not on the repository

### ISSUE THREAD

**Issue by wilmerbz** [jhomero10/TestModularis#1]
After cloning the repository, we are not able to compile it, as ModularisTestUnitTests references a file that doesn't exists.
      ModularisTestUnitTests 
           JobLoggerTest.cs

**Comment by wilmerbz** [comment]
Just by removing that file from the project, it compiles just fine.

**Comment by jhomero10** [comment]
During last push was fixed reported bug
